feat(raiko): put the tasks that cannot run in parallel into pending list
taikoxyz/raiko pull request #358
Opened 2024-09-05 03:23 UTC by smtmfft

<img width="453" alt="image" src="https://github.com/user-attachments/assets/9ca2c2e4-bb62-4530-8517-cc00fab8dcc5">

2024-09-09 07:14 UTC, petarvujovic98 requested changes

2024-09-09 07:14 UTC, petarvujovic98 commented on host/src/proof.rs
> +                        "task completed, current runing {:?}, pending: {:?}",
```suggestion
                        "task completed, current running {:?}, pending: {:?}",
```

2024-09-09 07:14 UTC, petarvujovic98 commented on host/src/proof.rs
> +                            "Task concurrency limit reached, current runing {:?}, pending: {:?}",
```suggestion
                            "Task concurrency limit reached, current running {:?}, pending: {:?}",
```

2024-09-09 10:53 UTC, smtmfft commented on host/src/lib.rs
> +    TaskComplete(ProofRequest),
you mean notify one-shot channel & let it send task in??

2024-10-11 06:19 UTC, johntaiko approved these changes

2024-10-14 09:11 UTC, petarvujovic98 commented on host/src/proof.rs
> +                    debug!("Message::TaskComplete: {:?}", req);
```suggestion
                    debug!("Message::TaskComplete: {req:?}");
```

2024-10-14 09:12 UTC, petarvujovic98 commented on host/src/proof.rs
> +                            running_task_count,
```suggestion
                            "Task concurrency limit reached, current running {running_task_count:?}, pending: {:?}",
```

2024-10-14 09:12 UTC, petarvujovic98 commented on host/src/proof.rs
> +                        info!("Running task {:?}", proof_request);
```suggestion
                        info!("Running task {proof_request:?}");
```

2024-10-14 09:12 UTC, petarvujovic98 commented on host/src/proof.rs
> +                    debug!("Message::Task proof_request: {:?}", proof_request);
```suggestion
                    debug!("Message::Task proof_request: {proof_request:?}");
```

2024-10-14 09:12 UTC, petarvujovic98 commented on host/src/proof.rs
> +                    debug!("Message::Cancel task: {:?}", key);
```suggestion
                    debug!("Message::Cancel task: {key:?}");
```

2024-10-14 12:18 UTC, petarvujovic98 approved these changes

2024-10-14 12:19 UTC, merged